### ISSUE TITLE
Text NER baseline issues

### ISSUE THREAD

**Issue by siddalmia** [asappresearch/slue-toolkit#16]
Hi @ankitapasad @fwu-asapp @sshon-asapp,

I really apologize for my many issue creation. I thought of running the baselines again but I think there are still some issues in the `slue_toolkit/text_ner/ner_deberta_modules.py` file. 

For example - 

1. https://github.com/asappresearch/slue-toolkit/blob/main/slue_toolkit/text_ner/ner_deberta_modules.py#L63 - Is trying to run regex on a list. But I think they can run only on string or bytes. 
2. https://github.com/asappresearch/slue-toolkit/blob/main/slue_toolkit/text_ner/ner_deberta_modules.py#L111 - Is trying to read a wrong file format. It should be `f"{split_name}.{label_type}.tsv"` instead.

Would it be possible to run a new bare slue-toolkit and see what all bugs pops up?

The command that I am trying to run is - 
```bash baselines/ner/nlp_scripts/ft-deberta.sh deberta-base combined```

Please ignore if you have already caught these issues. 
Thanks
Sid

**Comment by ankitapasad** [comment]
Hi Sid,

That's my bad, I broke it in one of the previous PRs. I have created a new PR #17 and have tested that the text NER training and evaluation works fine. Kindly refer to the PR comments for more details.

We appreciate the updates! Thank you for your patience.

**Comment by sshon-asapp** [comment]
I think this might be label conversion problem and this line might cause this issue. 
train_label="combined" in your case.
@ankitapasad can you check this?

https://github.com/asappresearch/slue-toolkit/blob/f53bf875d05b5020cf4cbf2989fe41e431cc564e/slue_toolkit/text_ner/ner_deberta.py#L30

**Comment by ankitapasad** [comment]
Hi @siddalmia @sshon-asapp 

Yes, that's right Suwon, the value of `train_label` must be changed to the appropriate option. Additionally, the evaluation code wasn't handling this combination correctly (training and evaluating on combined label tag): 
https://github.com/asappresearch/slue-toolkit/blob/f53bf875d05b5020cf4cbf2989fe41e431cc564e/slue_toolkit/text_ner/ner_deberta_modules.py#L451


I added PR #18 to resolve this.

- Ankita

**Comment by siddalmia** [comment]
Thanks @ankitapasad ! It's working now. 

```
 [0] → bash baselines/ner/nlp_scripts/eval-deberta.sh deberta-base dev combined combined
[micro-averaged F1] Precision: 0.85, recall: 0.89, fscore = 0.87
[micro-averaged F1] Precision: 0.89, recall: 0.92, fscore = 0.90
```
Just a minor suggestion. Maybe you can add a label `standard` or `label` next to the two scores? 

Thanks
Sid

**Comment by sshon-asapp** [comment]
@siddalmia Thanks for suggestion. Updated!
