### ISSUE TITLE
Inconsistent use of tabs and spaces

### ISSUE THREAD

**Issue by siddalmia** [asappresearch/slue-toolkit#3]
Hi, 

I think there is inconsistent use of tabs and spaces among the files in this toolkit like - 
`text_ner/ner_deberta.py` uses spaces and `text_ner/ner_deberta_modules.py` uses tabs. 

Would it be possible to apply black - https://pypi.org/project/black/ , to bring consistent formatting of files. 

Thanks
Sid

**Comment by fwu-asapp** [comment]
I close it since it has been fixed in #7.
