### ISSUE TITLE
preprocessed manifest files not on "assumed" location

### ISSUE THREAD

**Issue by machadowisck** [asappresearch/slue-toolkit#33]
[README](https://github.com/asappresearch/slue-toolkit/blob/f24b2213721b5fa2e619c46e2255ac2fbdf20665/README.md) points to fine-tuning command lines and add comments stating that "Assuming that the preprocessed manifest files are in manifest/slue-voxceleb for SLUE-VoxPopuli" the command should work. 

But, following the installation process described in the same README, no manifest folder or pre-processed files are created. 

It feels like I am missing a really obvious step. 

What is it that I'm missing? 

thanks in advance!

**Comment by sshon-asapp** [comment]
Hi. Can you please run the download script here?
https://github.com/asappresearch/slue-toolkit#download-and-pre-process-dataset
then you will see the folders in manifest/

**Comment by machadowisck** [comment]
Hey, @sshon-asapp ! Thank you very much for the quick reply... I had de dataset download script ran in another conda env and just had eyes to the data folder. If it was a snake... 

Thank you once again!
