### ISSUE TITLE
problem with prepare_voxpopuli.py

### ISSUE THREAD

**Issue by ramonsanabria** [asappresearch/slue-toolkit#34]
Hello,

Thanks for all your work. This toolkit is a great contribution to the community.

I am trying to reproduce some of your results, and when running `bash scripts/download_datasets.sh`, the script crashes in `slue_toolkit/prepare/prepare_voxpopuli.py` because at some point `label_str` in `get_label_lst()` get the value of nan. I leave the full error below.

Thanks again!

`    entity_pair_str = data_utils.prep_text_ner_tsv(
  File "/disk/scratch1/ramons/myapps/t2s-xling/myapps/slue-toolkit/slue_toolkit/prepare/data_utils.py", line 146, in prep_text_ner_tsv
    ner_labels_lst = get_label_lst(ner_labels_str, label_type)
  File "/disk/scratch1/ramons/myapps/t2s-xling/myapps/slue-toolkit/slue_toolkit/prepare/data_utils.py", line 33, in get_label_lst
    ner_labels_lst = label_str.strip("[[").strip("]]").split("], [")
AttributeError: 'float' object has no attribute 'strip`

**Comment by ankitapasad** [comment]
Hi @ramonsanabria 

I am unable to reproduce this error. The data preparation script works fine for me. Were you able to fix the issue?

Glad you find the toolkit and datasets useful!

**Comment by ramonsanabria** [comment]
Hey Ankita :)

Nice to hear from you! I hope all is well :)

I just checked it again now, and the error persists. Which python version are you using? I am using Python 3.10.9 (maybe it is too new?)

**Comment by ankitapasad** [comment]
Hey Ramon :)

Hm..that's strange! My environment is using Python 3.8.13. Do you want to try that?

Also, check my [latest PR](https://github.com/asappresearch/slue-toolkit/pull/36) for a re-implementation of `get_label_lst`, the function that's causing an error for you. See if that resolves it.

**Comment by ming024** [comment]
Hi all,

I came into this issue too. This is probably a problem with the Pandas version. A simple solutions is to change line 43-45 and 47-49 in [prepare_voxpopili.py](https://github.com/asappresearch/slue-toolkit/blob/f24b2213721b5fa2e619c46e2255ac2fbdf20665/slue_toolkit/prepare/prepare_voxpopuli.py#L43-L45) to 
```
    df = pd.read_csv(
        os.path.join(data_dir, f"slue-voxpopuli_{split}_blind.tsv"), sep="\t", keep_default_na=False
    )
else:
    df = pd.read_csv(
        os.path.join(data_dir, f"slue-voxpopuli_{split}.tsv"), sep="\t", keep_default_na=False
    )
```
