### ISSUE TITLE
Text NER Evaluation Pipeline doesn't seem to work

### ISSUE THREAD

**Issue by siddalmia** [asappresearch/slue-toolkit#6]
I am trying to run `baselines/ner/nlp_scripts/eval-deberta.sh` but it seems to be broken quite a bit. 

I have fixed some of the bugs, in the PR (https://github.com/asappresearch/slue-toolkit/pull/7) but there seems to be some more, which I am unable to fix comfortably and would require someone with expertise of this code to have a look - 
1) `eval_obj.get_scores` in `def eval(` of `slue_toolkit/text_ner/ner_deberta.py` seems to be passing `asr_val_dataset` which is set to `None` when `eval_asr` is set to `False`. 
2) This then causes an issue in `def get_scores` function in `slue_toolkit/text_ner/ner_deberta_modules.py`. As the `run_inference` invoked by get_scores uses `asr_val_dataset` in their `Dataloader`. 
3) The `self.get_entity_tags(` call in the `run_inference` function when `eval_asr` is set to `False` is also broken as this calls `self.get_tag_map(indices=True)` which seems to be calling an undefined variable `tag` in `tag2id_raw[pfx + tag]` 

Could you please review that PR and also suggest the changes for the above errors. I have kept the PR as `[WIP]` you can make edits to them as you feel fit. 

Thanks
Sid

**Comment by ankitapasad** [comment]
Hi Sid,

Thank you for contributing the corrections! 

Both the concerns mentioned above are resolved in PR [#10](https://github.com/asappresearch/slue-toolkit/pull/10).

Sorry for the trouble, we appreciate you bringing this to our attention!

**Comment by fwu-asapp** [comment]
I close it since it has been fixed in #7 and #10.
